vector_db:
  index_name: "trading-bot"

retriever:
  top_k: 3
  score_threshold: 0.5

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

llm:
  google:
    provider: "google"
    model_name: "gemini-1.5-pro"
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
  gpt:
    provider: "openai"
    model_name: "gpt-4o"

tools:
  tavily:
    max_results: 5

